name: chordify_lyrics
description: "A Flutter package to beautifully render and transpose chorded lyrics with ease — perfect for music apps, karaoke, or chord sheets."
version: 1.0.3
homepage: https://github.com/winminhtetz/chordify_lyrics
repository: https://github.com/winminhtetz/chordify_lyrics
documentation: https://github.com/winminhtetz/chordify_lyrics#readme

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
